# Generated by Django 4.1.13 on 2024-02-19 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0007_remove_patient_address_remove_patient_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('is_available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=50)),
                ('data_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorWiseReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_id', models.CharField(max_length=20)),
                ('data_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IPDDeposit',
            fields=[
                ('deposit_id', models.AutoField(primary_key=True, serialize=False)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='IPDDischarge',
            fields=[
                ('discharge_id', models.AutoField(primary_key=True, serialize=False)),
                ('discharge_date', models.DateField()),
                ('discharge_summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TPAReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('tpa_id', models.CharField(max_length=20)),
                ('transaction_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_beds', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WardWiseReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('ward', models.CharField(max_length=50)),
                ('data_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WardWiseBedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupied_beds', models.IntegerField()),
                ('available_beds', models.IntegerField()),
                ('report_date', models.DateField(auto_now_add=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipd.ward')),
            ],
        ),
        migrations.CreateModel(
            name='IPDRegistration',
            fields=[
                ('admission_id', models.AutoField(primary_key=True, serialize=False)),
                ('admission_date', models.DateField()),
                ('bed', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ipd.bed')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('ward', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ipd.ward')),
            ],
        ),
        migrations.CreateModel(
            name='IPDDischargeReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_details', models.TextField()),
                ('discharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipd.ipddischarge')),
            ],
        ),
        migrations.AddField(
            model_name='ipddischarge',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipd.ipdregistration'),
        ),
        migrations.CreateModel(
            name='IPDDepositReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_details', models.TextField()),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipd.ipddeposit')),
            ],
        ),
        migrations.AddField(
            model_name='ipddeposit',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipd.ipdregistration'),
        ),
        migrations.CreateModel(
            name='IPDAdmitReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_details', models.TextField()),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipd.ipdregistration')),
            ],
        ),
        migrations.CreateModel(
            name='BedStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_status', models.BooleanField()),
                ('update_date', models.DateField(auto_now_add=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipd.bed')),
            ],
        ),
        migrations.CreateModel(
            name='BedBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipd.bed')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='BedAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('bed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ipd.bed')),
            ],
        ),
        migrations.CreateModel(
            name='BedAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipd.ipdregistration')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipd.bed')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipd.ward'),
        ),
    ]
