# Generated by Django 4.1.13 on 2024-02-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
