# Generated by Django 4.1.13 on 2024-02-20 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0004_ipdregistration_discharge_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdregistration',
            name='is_discharged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ipddischarge',
            name='admission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ipd.ipdregistration'),
        ),
    ]
