# Generated by Django 4.1.13 on 2024-04-10 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_remove_patient_address_remove_patient_age_and_more'),
        ('ipd', '0005_ipdregistration_is_discharged_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
