# Generated by Django 4.1.13 on 2024-04-24 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0007_bed_owner_bedallocation_owner_bedavailability_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdregistration',
            name='bed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ipd.bed'),
        ),
    ]
