# Generated by Django 4.1.13 on 2024-07-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffleave',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staffperformance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staffshift',
            name='user',
        ),
        migrations.DeleteModel(
            name='StaffAttendance',
        ),
        migrations.DeleteModel(
            name='StaffLeave',
        ),
        migrations.DeleteModel(
            name='StaffPerformance',
        ),
        migrations.DeleteModel(
            name='StaffShift',
        ),
    ]
