# Generated by Django 4.1.13 on 2024-07-01 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_owwner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='owwner',
        ),
    ]
