# Generated by Django 4.1.13 on 2024-07-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.DateTimeField(default=None),
        ),
    ]
