# Generated by Django 4.1.13 on 2024-07-02 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0013_alter_patientbilling_owner_and_more'),
        ('inventory', '0004_equipment_owner_inventoryitem_owner_medicine_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='expiration_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='medicine_manufacturer',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='medicine_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.CreateModel(
            name='MedicineEquipmentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField(default=0)),
                ('usage_date', models.DateField(auto_now_add=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medicine')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
