# Generated by Django 4.1.13 on 2024-06-21 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('Relationship', models.CharField(blank=True, max_length=100)),
                ('fullname', models.CharField(blank=True, max_length=255)),
                ('blood', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone_no', models.CharField(blank=True, max_length=20)),
                ('referred', models.CharField(blank=True, max_length=255)),
                ('allergy', models.TextField(blank=True)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('facility_code', models.CharField(blank=True, max_length=100)),
                ('membernum', models.CharField(blank=True, max_length=100)),
                ('Insurance_name', models.CharField(blank=True, max_length=100)),
                ('card_num', models.CharField(blank=True, max_length=100)),
                ('Insurance_Provider', models.CharField(blank=True, max_length=100)),
                ('Gender', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('Register_Date', models.DateField()),
                ('PinCode', models.CharField(blank=True, max_length=10, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentInformation',
            fields=[
                ('TreatmentID', models.AutoField(primary_key=True, serialize=False)),
                ('TreatmentDetails', models.TextField()),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('owner', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientVisitList',
            fields=[
                ('VisitID', models.AutoField(primary_key=True, serialize=False)),
                ('VisitDate', models.DateField()),
                ('Reason', models.TextField()),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('owner', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientReminder',
            fields=[
                ('ReminderID', models.AutoField(primary_key=True, serialize=False)),
                ('ReminderDetails', models.TextField()),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('owner', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientLedger',
            fields=[
                ('LedgerID', models.AutoField(primary_key=True, serialize=False)),
                ('TransactionDetails', models.TextField()),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('owner', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('HistoryID', models.AutoField(primary_key=True, serialize=False)),
                ('MedicalHistoryDetails', models.TextField()),
                ('TreatmentDetails', models.TextField()),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('owner', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientBilling',
            fields=[
                ('BillingID', models.AutoField(primary_key=True, serialize=False)),
                ('InvoiceDetails', models.TextField()),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('owner', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
