# Generated by Django 4.1.13 on 2024-04-19 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0007_remove_patient_address_remove_patient_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='owner',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
