# Generated by Django 4.1.13 on 2024-04-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_alter_patient_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='PatientID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
