# Generated by Django 4.1.13 on 2024-04-19 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hos_login', '0006_alter_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Custom_User',
        ),
    ]
