# Generated by Django 4.1.13 on 2024-04-19 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hos_login', '0008_custom_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
