# Generated by Django 4.1.13 on 2024-04-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos_login', '0009_custom_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
