# Generated by Django 4.1.13 on 2024-02-01 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
