# Generated by Django 4.1.13 on 2024-02-27 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_dashboard', '0002_delete_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CNFT',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
