# Generated by Django 4.1.13 on 2024-07-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctor_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=10),
        ),
    ]
